### ISSUE TITLE
Acceleration and day-start end charging

### ISSUE THREAD

**Issue by mihirnimgade** [UBC-Solar/Simulation#33]
Combining the acceleration implementation and the day-start end charging implementation is causing some strange speed curves. It makes sense why the speed curves look the way they do but this is a deep-seated issue that will not be easy to solve. 

Since we are applying the acceleration in the assumption stage and then applying the day-start end charging during the simulation stage, there is some sort of disparity. Maybe the day-start end charging implementation needs to be moved to the assumption stage. 
![strange_speed_curve](https://user-images.githubusercontent.com/40799875/99695937-2a793b00-2ab4-11eb-8137-57edb746ce6c.png)

**Comment by chrischang5** [comment]
![proof that car charges in morning  moving time changed from 12 to 18](https://user-images.githubusercontent.com/64388914/112734266-e84c8400-8f01-11eb-9a95-8ec9a9a4524b.png)

Demonstration of car charging during allocated charging time in the scenario that the driving time is changed to 1:00 to 18:00 rather than 9:00 to 18:00. This is done to make the charging behaviour more clear, otherwise it's not as evident that this scenario is handled at all

**Comment by chrischang5** [comment]
![Inkedproof of charge after stopping, clipping issue_LI](https://user-images.githubusercontent.com/64388914/112734455-18485700-8f03-11eb-9030-d2cd01b14c93.jpg)

Demonstration of car charging after stopping in the **day's end**. See the red circled area for this.
